// Builds the SQL that seeds the stock-profile tables from the tested TypeScript
// table, so the two can't drift. Written to disk by gen-seed.ts and checked by test/db.test.ts.
import { MACHINE_ID as MACHINE, STOCK_PROFILES, stockProfileId as slug } from "../src/adapters/kaffelogic/startingProfiles.js";

const q = (v: string | number | boolean | null | undefined) =>
  v === null || v === undefined ? "null" : typeof v === "string" ? `'${v.replace(/'/g, "''")}'` : String(v);
const seconds = (mmss: string) => {
  const [m, s] = mmss.split(":").map(Number);
  return m * 60 + s;
};

function intent(name: string) {
  const alt = name.match(/^(\d+)-(\d+)m (RTD|Rest)$/);
  return {
    altMin: alt ? Number(alt[1]) : null,
    altMax: alt ? Number(alt[2]) : null,
    drinkWhen: alt ? (alt[3] === "Rest" ? "rest" : "soon") : null,
    process: name === "KL Washed" ? "washed" : name === "KL Natural" ? "natural" : null,
    species: name.startsWith("Robusta") ? "robusta" : null,
    decaf: name === "Decaf",
  };
}

export function generateSeed(): string {
const out: string[] = [
  "-- Generated by scripts/gen-seed.ts from src/adapters/kaffelogic/startingProfiles.ts. Do not edit by hand.",
  `insert into machine (id, name) values (${q(MACHINE)}, 'Kaffelogic Nano 7');`,
  "",
];
for (const p of Object.values(STOCK_PROFILES)) {
  const i = intent(p.name);
  out.push(
    "insert into stock_profile (id, machine_id, name, version, family, altitude_min_m, altitude_max_m, drink_when, process, species, decaf, roast_levels_c, expect_first_crack_c, selectable) values " +
      `(${[slug(p.name), MACHINE, p.name, p.version, p.family, i.altMin, i.altMax, i.drinkWhen, i.process, i.species, i.decaf].map(q).join(", ")}, ` +
      `'{${p.roastLevels.join(",")}}', ${q(p.expectFirstCrack)}, ${q(p.selectable ?? true)});`,
  );
  for (const [goal, l] of Object.entries(p.levels)) {
    const dev = p.developmentTarget?.[goal as keyof typeof p.levels];
    const rise = p.riseAfterCrack?.[goal as keyof typeof p.levels];
    out.push(
      "insert into stock_profile_level (profile_id, goal, level, end_temp_c, ends_at_s, dev_target_min_pct, dev_target_max_pct, rise_after_crack_min_c, rise_after_crack_max_c) values " +
        `(${[slug(p.name), goal, l.level, l.endTemp, seconds(l.endsAt), dev?.[0], dev?.[1], rise?.[0], rise?.[1]].map(q).join(", ")});`,
    );
  }
  out.push("");
}
return out.join("\n") + "\n";
}

